//
//  macifomliteConstants.h
//  Battle Kid 2 Demo
//
//  Created by Auston Stewart on 7/17/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#ifndef Battle_Kid_2_Demo_macifomliteConstants_h
#define Battle_Kid_2_Demo_macifomliteConstants_h

#define VIDEO_PIXEL_WIDTH 256
#define VIDEO_PIXEL_HEIGHT 256
#define NES_VISIBLE_PIXELS_WIDTH 256
#define NES_VISIBLE_PIXELS_HEIGHT 224

#define VIDEO_HORIZONTAL_OFFSET_IPHONE_PORTRAIT 32
#define VIDEO_VERTICAL_OFFSET_IPHONE_PORTRAIT 224
#define VIDEO_WIDTH_IPHONE_PORTRAIT 256
#define VIDEO_HEIGHT_IPHONE_PORTRAIT 224

#define VIDEO_HORIZONTAL_OFFSET_IPHONE5_PORTRAIT 32
#define VIDEO_VERTICAL_OFFSET_IPHONE5_PORTRAIT 268
#define VIDEO_WIDTH_IPHONE5_PORTRAIT 256
#define VIDEO_HEIGHT_IPHONE5_PORTRAIT 224

#define VIDEO_HORIZONTAL_OFFSET_IPAD_PORTRAIT 0
#define VIDEO_VERTICAL_OFFSET_IPAD_PORTRAIT 286
#define VIDEO_WIDTH_IPAD_PORTRAIT 768
#define VIDEO_HEIGHT_IPAD_PORTRAIT 672

#define VIDEO_HORIZONTAL_OFFSET_IPHONE_LANDSCAPE 112
#define VIDEO_VERTICAL_OFFSET_IPHONE_LANDSCAPE 92
#define VIDEO_HEIGHT_IPHONE_LANDSCAPE 224
#define VIDEO_WIDTH_IPHONE_LANDSCAPE 256

#define VIDEO_HORIZONTAL_OFFSET_IPHONE5_LANDSCAPE 84
#define VIDEO_VERTICAL_OFFSET_IPHONE5_LANDSCAPE 20
#define VIDEO_WIDTH_IPHONE5_LANDSCAPE 400
#define VIDEO_HEIGHT_IPHONE5_LANDSCAPE 300

#define VIDEO_HORIZONTAL_OFFSET_IPAD_LANDSCAPE 0
#define VIDEO_VERTICAL_OFFSET_IPAD_LANDSCAPE 0
#define VIDEO_WIDTH_IPAD_LANDSCAPE 1024
#define VIDEO_HEIGHT_IPAD_LANDSCAPE 768

#define DPAD_LEFT_OFFSET_IPHONE 0.f
#define DPAD_BOTTOM_OFFSET_IPHONE 0.f
#define DPAD_LEFT_OFFSET_IPAD 4.f
#define DPAD_BOTTOM_OFFSET_IPAD 20.f
#define DPAD_SECTION_SIZE_IPHONE 55.f
#define DPAD_SECTION_SIZE_IPAD 102.f
#define DPAD_DEADSPACE_SIZE_IPAD 40.f
#define DPAD_DEADSPACE_SIZE_IPHONE 40.f
#define BUTTON_SECTION_SIZE_IPHONE 75.f
#define BUTTON_SECTION_SIZE_IPAD 120.f
#define SHOULDER_BUTTON_WIDTH_IPHONE 100.f
#define SHOULDER_BUTTON_WIDTH_IPAD 200.f
#define BUTTONS_RIGHT_OFFSET_IPHONE 0.f
#define BUTTONS_RIGHT_OFFSET_IPAD 4.f
#define BUTTONS_BOTTOM_OFFSET_IPHONE 0.f
#define BUTTONS_BOTTOM_OFFSET_IPAD 24.f

#define DPAD_LEFT_OFFSET_IPHONE_TV 4.f
#define DPAD_BOTTOM_OFFSET_IPHONE_TV 28.f
#define DPAD_SECTION_SIZE_IPHONE_TV 92.f
#define DPAD_DEADSPACE_SIZE_IPHONE_TV 40.f
#define BUTTON_SECTION_SIZE_IPHONE_TV 120.f
#define BUTTONS_RIGHT_OFFSET_IPHONE_TV (-20.f)
#define BUTTONS_BOTTOM_OFFSET_IPHONE_TV 20.f

#define SKIN_ARTFILE_PREFIX @"macifomlite"

#endif
